import { FEATURES, LEARNING_STEPS, NEXT_TOPIC_GROUPS, SITE, TOPIC_GROUPS } from '../data/siteContent'
import { PageContainer, SectionTitle, type Navigate } from '../components/site/SiteLayout'
import { GlossaryText } from '../components/ui/GlossaryText'

function PrimaryButton({ children, onClick }: { children: string; onClick: () => void }) {
  return <button type="button" onClick={onClick} className="rounded-xl bg-cyan-600 px-5 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-cyan-700">{children}</button>
}

function SimulationNote({ onNavigate }: { onNavigate: Navigate }) {
  return <div className="rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm leading-6 text-amber-900"><span className="font-bold">教育用シミュレーションについて。</span> <GlossaryText text="このサイトはITインフラの仕組みを理解するための教育用シミュレーションです。実際のネットワーク通信やコンピュータ内部の処理を完全に再現するものではありません。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></div>
}

export function HomePage({ onNavigate }: { onNavigate: Navigate }) {
  return <PageContainer>
    <section className="grid items-center gap-10 py-5 lg:grid-cols-[1.08fr_.92fr] lg:py-12">
      <div><p className="eyebrow">3D INTERACTIVE LEARNING</p><h1 className="mt-4 text-4xl font-bold leading-tight tracking-tight text-slate-900 sm:text-5xl">見えないITインフラを、<br />見て理解する。</h1><p className="mt-6 max-w-xl text-base leading-8 text-slate-600"><GlossaryText text="Webサイトへアクセスしたとき、PCの中からサーバーまで何が起きているのか。3D空間を探索しながら、データの流れを追って学べます。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p><div className="mt-8 flex flex-wrap gap-3"><PrimaryButton onClick={() => onNavigate('/visualizer')}>シミュレーションを始める</PrimaryButton><button type="button" onClick={() => onNavigate('/about')} className="rounded-xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-700 transition hover:border-cyan-400 hover:text-cyan-700">このサイトについて</button></div></div>
      <div className="rounded-3xl border border-cyan-100 bg-slate-50 p-5 shadow-sm"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className="eyebrow">URL ACCESS FLOW</span><span className="rounded-full bg-cyan-50 px-2 py-1 text-[10px] font-bold text-cyan-700">SIMULATION</span></div><div className="mt-7 grid gap-3"><div className="flow-node flow-node-pc">PC <span>Application / OS / NIC</span></div><div className="flow-line" /><div className="flow-node flow-node-router">Router <span>宛先IPから次の経路を選ぶ</span></div><div className="flow-line" /><div className="flow-node flow-node-server">Web Server <span>データを取り出して処理する</span></div></div></div><p className="mt-4 px-1 text-sm leading-6 text-slate-600"><GlossaryText text="遠くから見ると抽象的に、中に入るほど具体的に。通信の全体像から、フレームやビットまで進めます。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></div>
    </section>

    <section className="border-t border-slate-200 py-16"><SectionTitle eyebrow="WHAT YOU CAN LEARN" title="このサイトで分かること" lead="用語を単独で覚えるのではなく、Webアクセスという一つの流れの中で関係を確かめます。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /><div className="mt-9 grid gap-4 sm:grid-cols-2"><>{FEATURES.map(feature => <article key={feature.title} className="panel p-6"><p className="eyebrow">{feature.tag}</p><h2 className="mt-3 text-lg font-bold text-slate-900">{feature.title}</h2><p className="mt-2 text-sm leading-7 text-slate-600"><GlossaryText text={feature.body} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></article>)}</></div></section>

    <section className="border-t border-slate-200 py-16"><SectionTitle eyebrow="HOW TO LEARN" title="3Dで学ぶ仕組み" lead="3Dは装飾ではなく、目に見えない仕組みの位置や関係を理解するために使います。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /><div className="mt-9 grid gap-4 md:grid-cols-4">{LEARNING_STEPS.map(([title, body], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-cyan-50 text-sm font-bold text-cyan-700">{index + 1}</span><h2 className="mt-4 font-bold text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600"><GlossaryText text={body} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></article>)}</div><p className="mt-8 text-center text-lg font-semibold text-cyan-800">遠くから見ると抽象的に、中に入るほど具体的に。</p></section>

    <section className="border-t border-slate-200 py-16"><SectionTitle eyebrow="FOR LEARNERS" title="こんな人に向いています" /><div className="mt-8 flex flex-wrap gap-3">{['ネットワークを勉強し始めた人', 'ITインフラを学ぶ学生', 'TCP/IPを直感的に理解したい人', 'Web通信の裏側を知りたい人', 'ITエンジニアを目指す初心者'].map(item => <span key={item} className="rounded-full border border-slate-200 bg-white px-4 py-2 text-sm text-slate-700">{item}</span>)}</div></section>

    <section className="border-t border-slate-200 py-16"><SimulationNote onNavigate={onNavigate} /><div className="mt-8 rounded-3xl border border-cyan-100 bg-cyan-50 p-8 text-center"><h2 className="text-2xl font-bold tracking-tight text-slate-900">通信の流れを、3Dでたどる。</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-7 text-slate-600"><GlossaryText text="3つのURLから接続先を選び、通信の流れを確認してみましょう。実際に外部へアクセスすることはありません。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p><div className="mt-6"><PrimaryButton onClick={() => onNavigate('/visualizer')}>シミュレーションを始める</PrimaryButton></div></div></section>
  </PageContainer>
}

export function AboutPage({ onNavigate }: { onNavigate: Navigate }) { return <PageContainer><SectionTitle title="このサイトについて" lead="普段は目に見えないITインフラの内部構造や通信の流れを、3D・アニメーション・階層探索によって直感的に理解するための教育用Webアプリです。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /><div className="mt-12 grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="space-y-6 text-base leading-8 text-slate-600"><p><GlossaryText text="Webサイトへアクセスするだけでも、PC内部、OS、ネットワークスタック、NIC、ルーター、DNS、TCP/IP、Ethernet、サーバーなど、多くの仕組みが連携しています。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p><p>このサイトでは、それらを3D空間やアニメーションでシミュレーションし、「何がどこで起きているのか」を一つのデータの流れとして理解できることを目指しています。</p><p>個人開発の教育プロジェクトとしてβ版を公開しています。教育用に一部を簡略化しており、今後は資格学習にも活かせる教材へ段階的に広げる予定です。</p></div><SimulationNote onNavigate={onNavigate} /></div><section className="mt-16 border-t border-slate-200 pt-12"><SectionTitle eyebrow="WHY THIS PROJECT" title="開発目的" /><p className="mt-6 max-w-3xl text-base leading-8 text-slate-600"><GlossaryText text="ITインフラは重要な技術である一方、実際の処理が目に見えないため、初心者にとって全体像をつかみにくい分野です。用語を個別に覚えるのではなく、一つのデータがどのように処理され、どの機器を通り、どのプロトコルによって運ばれるのかをシミュレーションで示すことで、仕組み同士の関係を理解しやすくします。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-500">本サイトは各資格試験実施団体の公式教材ではありません。</p></section><section className="mt-16 grid gap-4 md:grid-cols-3">{[['視覚的に理解する', '文章や図だけでは捉えにくい仕組みを、3D空間とアニメーションで表現します。'], ['全体と詳細をつなげる', 'Internet全体から、PC内部、Protocol、Header、bitまで、段階的に掘り下げます。'], ['「なぜ」を理解する', '用語の定義だけではなく、なぜその仕組みが必要なのかを重視します。']].map(([title, body]) => <article key={title} className="panel p-6"><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-600"><GlossaryText text={body} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></article>)}</section></PageContainer> }

export function GuidePage({ onNavigate }: { onNavigate: Navigate }) { const steps = [['1. URLを選ぶ', 'シミュレーション画面の左上で、接続先のWebサイトを選び、「シミュレーションを開始」を押します。'], ['2. 通信を追う', '中央の3D空間で、データの移動とネットワーク機器を確認できます。'], ['3. 右側を見る', '現在どの通信処理が行われているかを、タイムラインと説明で確認します。'], ['4. データ構造を見る', '左側でTCP Segment、IP Packet、Ethernet Frameなどの構造を確認します。'], ['5. 中へ入る', 'PCや各プロトコルを選択し、内部構造まで探索します。']] as const; return <PageContainer><SectionTitle title="使い方" lead="まずURLアクセスの全体を見て、気になる機器やデータ構造を選び、内部の世界へ進みます。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /><ol className="mt-10 max-w-3xl space-y-4">{steps.map(([title, body]) => <li key={title} className="panel flex gap-5 p-6"><span className="mt-0.5 text-2xl font-bold text-cyan-600">{title.slice(0, 1)}</span><div><h2 className="font-bold text-slate-900">{title.slice(3)}</h2><p className="mt-2 text-sm leading-7 text-slate-600"><GlossaryText text={body} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></div></li>)}</ol><div className="mt-10"><SimulationNote onNavigate={onNavigate} /></div><div className="mt-8"><PrimaryButton onClick={() => onNavigate('/visualizer')}>シミュレーションを始める</PrimaryButton></div></PageContainer> }

export function TopicsPage({ onNavigate }: { onNavigate: Navigate }) { return <PageContainer><SectionTitle title="学べる内容" lead="現在、シミュレーション画面で探索・参照できる対象をまとめています。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /><div className="mt-10 grid gap-4 sm:grid-cols-2">{TOPIC_GROUPS.map(group => <section key={group.title} className="panel p-6"><p className="eyebrow">TOPIC</p><h2 className="mt-2 text-lg font-bold text-slate-900">{group.title}</h2><ul className="mt-4 flex flex-wrap gap-2">{group.items.map(item => <li key={item} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm text-slate-700"><GlossaryText text={item} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></li>)}</ul></section>)}</div><div className="mt-10 rounded-2xl border border-slate-200 bg-slate-50 p-6"><h2 className="font-bold text-slate-900">詳細教材を深めていくテーマ</h2><p className="mt-2 text-sm leading-7 text-slate-600"><GlossaryText text="TLSは通信Timelineで、IPv6とNATは用語解説で一部に触れています。一方で、それぞれの内部探索や詳細なアニメーション教材は今後追加予定です。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p><div className="mt-5 grid gap-3 md:grid-cols-3">{NEXT_TOPIC_GROUPS.map(topic => <article key={topic.title} className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-900"><GlossaryText text={topic.title} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></h3><p className="mt-2 text-xs leading-6 text-slate-600"><GlossaryText text={topic.body} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></article>)}</div><div className="mt-5"><PrimaryButton onClick={() => onNavigate('/visualizer')}>シミュレーションを開く</PrimaryButton></div></div></PageContainer> }

export function NotesPage({ onNavigate }: { onNavigate: Navigate }) { return <PageContainer><SectionTitle title="教材上の注意・簡略化について" lead="正確さを大切にしつつ、全体の関係を学びやすくするために一部を抽象化しています。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /><div className="mt-10 space-y-4">{[['教育用の簡略化', '実際のコンピュータやInternetは非常に複雑です。このサイトでは全体像を理解しやすくするため、処理や機器構成を一部簡略化して表現しています。'], ['実際の通信との差', '通信経路、パケットの動き、タイミングなどは教育目的のモデルです。選択したURLに実際にアクセスしたり、DNS問い合わせやパケット送信を行ったりすることはありません。'], ['代表的なHTTPSの例', '本シミュレーションでは、HTTPSをTCP + TLS上で利用する代表的な通信例を扱っています。実際にはHTTP/3でQUIC / UDPが利用される場合など、通信方式は環境によって異なります。'], ['プロトコルの扱い', '各プロトコルの説明は基本的な仕組みを理解することを目的としており、仕様のすべてを網羅するものではありません。'], ['資格試験との関係', '本サイトは各資格試験実施団体の公式教材ではありません。資格学習の補助として利用する場合も、公式の出題範囲や教材を確認してください。']].map(([title, body]) => <article key={title} className="panel p-6"><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600"><GlossaryText text={body} onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></article>)}</div></PageContainer> }

export function PrivacyPage({ onNavigate }: { onNavigate: Navigate }) { return <PageContainer><SectionTitle title="プライバシーについて" lead="β版で扱う情報と、現在行っていないデータ処理についての説明です。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /><div className="mt-10 max-w-3xl space-y-5 text-sm leading-7 text-slate-600"><article className="panel p-6"><h2 className="text-lg font-bold text-slate-900">現在のデータ処理</h2><p className="mt-3">本サイトはアカウント登録、広告、決済、外部アクセス解析を利用していません。学習の進行や選択内容はブラウザ内だけで扱い、外部のデータベースへ保存しません。</p></article><article className="panel p-6"><h2 className="text-lg font-bold text-slate-900">URL選択について</h2><p className="mt-3"><GlossaryText text="URL選択機能は教育目的のシミュレーションです。選択されたURLに対して、実際のHTTP通信、DNS問い合わせ、パケット送信、外部ページへの自動遷移を行いません。" onOpenTerm={(termId) => onNavigate(`/glossary/${termId}`)} /></p></article><article className="panel p-6"><h2 className="text-lg font-bold text-slate-900">今後の変更</h2><p className="mt-3">アクセス解析、問い合わせ機能、アカウントなどを将来導入する場合は、導入前にこのページと利用規約を実際の仕様に合わせて更新します。</p></article></div></PageContainer> }

export const PAGE_META = {
  '/': ['ITインフラシミュレーション | 通信の仕組みを3Dで学ぶ', SITE.description],
  '/visualizer': ['シミュレーション | Infrastructure Simulator', 'URLアクセス時に起きる通信とITインフラを、3Dで探索する教育用シミュレーション。'],
  '/glossary': ['用語集 | Infrastructure Simulator', 'ITインフラとWeb通信の用語を、Webアクセス・IP・LAN・回線などの階層から調べられる用語集。'],
  '/about': ['このサイトについて | Infrastructure Simulator', 'ITインフラを3D・アニメーション・階層探索で学ぶ教育プロジェクトについて。'],
  '/guide': ['使い方 | Infrastructure Simulator', 'ITインフラシミュレーションの使い方と、3D探索・通信シミュレーションの見方。'],
  '/topics': ['学べる内容 | Infrastructure Simulator', '現在探索できるPC、ネットワーク機器、プロトコル、データ構造の一覧。'],
  '/notes': ['教材上の注意 | Infrastructure Simulator', '教育用シミュレーションにおける簡略化と実際の通信との差について。'],
  '/privacy': ['プライバシーについて | Infrastructure Simulator', 'β版でのデータ処理と、実際の通信を行わない教育用シミュレーションについて。'],
  '/terms': ['利用規約 | Infrastructure Simulator', 'Infrastructure Simulator β版の利用に関する基本的な注意事項。'],
  '/404': ['ページが見つかりません | Infrastructure Simulator', 'お探しのページは見つかりませんでした。'],
} as const
